### ISSUE TITLE
TypeError: Cannot read property 'style' of null     at new ChannelBtn

### ISSUE THREAD

**Issue by deadcombo** [Skullbite/collapsible-ui#2]
```
[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'style' of null
    at new ChannelBtn (\src\Powercord\plugins\collapsible-ui\components\ChannelBtn.jsx:8:73)
    at \src\Powercord\plugins\bdCompat\plugins\CrashRecovery.plugin.js:363:17 
Component stack:
     at m (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5455:492)
    at div
    at p (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:1932:171)
    at section
    at E (https://canary.discord.com/assets/56e548d56b583c2656b9.js:949:128)
    at t (https://canary.discord.com/assets/56e548d56b583c2656b9.js:346:428)
    at div
    at t (https://canary.discord.com/assets/07dd2adb3838af187d09.js:63:923)
    at e (https://canary.discord.com/assets/9b160eb6a693f9ef8c45.js:48:760)
    at https://canary.discord.com/assets/0e01289285cd4c91051b.js:63:44
    at https://canary.discord.com/assets/07dd2adb3838af187d09.js:76:594
    at re (https://canary.discord.com/assets/07dd2adb3838af187d09.js:38:645)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5429:926)
    at c (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:1790:213)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5432:10)
    at div
    at div
    at div
    at Ae (https://canary.discord.com/assets/07dd2adb3838af187d09.js:42:138)
    at div
    at l (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:4042:605)
    at t (https://canary.discord.com/assets/07dd2adb3838af187d09.js:163:708)
    at div
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3951:564)
    at t (https://canary.discord.com/assets/07dd2adb3838af187d09.js:166:312)
    at z (https://canary.discord.com/assets/07dd2adb3838af187d09.js:167:857)
    at div
    at t (https://canary.discord.com/assets/07dd2adb3838af187d09.js:393:7)
    at k (https://canary.discord.com/assets/07dd2adb3838af187d09.js:146:188)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5429:926)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5432:10)
    at t (https://canary.discord.com/assets/07dd2adb3838af187d09.js:251:931)
    at u (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3642:833)
    at Suspense
    at d
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5429:926)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5432:10)
    at div
    at y (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3168:435)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3135:414)
    at VerificationLayerProvider
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3135:414)
    at AppLayerProvider
    at p (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:1932:171)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:700:286)
    at T (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:702:687)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:703:168)
    at u (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3642:833)
    at h (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:688:24)
    at te (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:691:601)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:746:10)
    at u (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:3641:772)
    at https://canary.discord.com/assets/322bed98d92ae480e8d9.js:4106:30
    at H (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5243:700)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5426:570)
    at t (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:5382:817)
    at f (https://canary.discord.com/assets/322bed98d92ae480e8d9.js:2176:239)
_log @ VM1511 C:\Programs\powercord\src\Powercord\plugins\bdCompat\plugins\0PluginLibrary.plugin.js:1749
```

**Comment by Skullbite** [comment]
[Already Fixed](https://github.com/Skullbite/collapsible-ui/commit/5addcd71744e36a2faf072f408999813fa6bf6f1)
